name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.011b2cce-5ee2-4ff9-93f2-f7bc8c712f9f}}
          heroku_app_name: ${{secrets.rajlecg2}}
          heroku_email: ${{secrets.naveenreddy694@hotmail.com}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: ${{secrets.https://gist.githubusercontent.com/rjar6545/f779cdc456809e014e216e1438245a3c/raw/saveRajHere.envL}}
